default:
  image:
    python:3.11

build-doc:
  stage: deploy
  before_script:
    - pip install .[doc]
  script:
  - pip install -U sphinx
  - sphinx-build -b html docs/source public
  only:
  - branches

