name: CI

on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[linter]
    - name: Analysing the code with flake8
      run: |
        pylint $(git ls-files '*.py')
        python -m flake8 xarray_eop tests --output-file linter.txt
